name: custom_card_module
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  provider: ^6.0.5
  photo_view: ^0.14.0
  dio: ^5.3.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:     
    - assets/icons/
    - assets/images/

  fonts:
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Light.ttf
          weight: 300
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
          weight: 400
        - asset: assets/fonts/AvenirNextLTPro-Medium.otf
          weight: 500
        - asset: assets/fonts/AvenirNextLTPro-SemiBold.otf
          weight: 600  
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 700